site_name: Servidor en tiempo real de datos GTFS

nav:
  - Inicio: index.md
  - Desarrollo: development.md
  - Equipo de abordo: obe.md
  - API: api.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: es
  logo: assets/logos/b.png
  favicon: assets/logos/b.png
  palette:
    scheme: ucr
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.code.select

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format